apiVersion: v1
entries:
  mysql:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-12-15T17:26:24.1404452+05:30"
    description: A Helm chart for mysql database
    digest: 7fe680a9ec0d8eb8d9a2d8aa9dbe9c09f3f850056e1f4be96c127aa375fcd446
    name: mysql
    type: application
    urls:
    - mysql-0.1.0.tgz
    version: 0.1.0
  todo-api:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-12-15T17:26:24.1414452+05:30"
    dependencies:
    - condition: database.enabled
      name: mysql
      repository: https://vijaynvb.github.io/todoapi/Helm/TodoApi_MySQL/mysql/charts
      version: 0.1.0
    description: A Helm chart for deploy todo application
    digest: 71dcf2e95af121c3b523b79855e5c211ec026f3b484221e893ec8de3dc85c577
    name: todo-api
    type: application
    urls:
    - todo-api-0.1.0.tgz
    version: 0.1.0
generated: "2023-12-15T17:26:24.1394427+05:30"
